name: 构建和部署

# workflow的触发事件，这里代表main分支的push事件触发
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

      - name: Send Mail 发送邮件
        uses: bingblue/send-nodemailer@master
        with:
          user: '${{ secrets.EMAIL_USERNAME }}'
          pass: '${{ secrets.EMAIL_PASSWORD }}'
          host: 'smtp.gmail.com'
          port: 465
          secure: true
          from: '构建部署 <maosenyang00@gmail.com>'
          to: 1960638223@qq.com,1694181697@qq.com

          # 判断是否有失败的工作流，如果有则发送“Failed：部署失败”邮件，否则发送“Success：部署成功！”邮件
          if: ${{ job.status != 'success' }}
          subject: Failed：部署失败
          html: <h2>部署失败请重新检查代码!workflow名称为 ${{ github.workflow }}。</h2>

          else:
            subject: Success：部署成功！
            html: <h2>构建部署执行完毕！workflow名称为 ${{ github.workflow }}。</h2>
