name: 构建和部署

# workflow的触发事件，这里代表main分支的push事件触发
on:
  push:
    branches: [ main ]

jobs:
  # 修改任务名称
  deploy-to-ghpages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

      # 判断工作流是否成功，并发送邮件通知
      - name: Send Notification Email 发送邮件通知
        if: always()
        uses: dawidd6/action-send-mail@v3.0.0
        env:
          SMTP_SERVER_ADDRESS: smtp.gmail.com
          SMTP_SERVER_PORT: 465
          SMTP_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM_ADDRESS: maosenyang00@gmail.com
          EMAIL_TO_ADDRESS: 1960638223@qq.com,1694181697@qq.com
        with:
          server_address: $SMTP_SERVER_ADDRESS
          server_port: $SMTP_SERVER_PORT
          subject: ${{ job.status }}：部署${{ job.status == 'success' && '成功！' || '失败' }}
          body: ${{ job.status == 'success' && '所有工作流成功执行完毕！' || '部署失败请重新检查代码' }}，workflow名称为 ${{ github.workflow }}。
