name: 构建和部署

# workflow的触发事件，这里代表main分支的push事件触发
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

      - name: Send Mail 发送邮件
        uses: bingblue/send-nodemailer@master
        with:
          user: '${{ secrets.EMAIL_USERNAME }}'
          pass: '${{ secrets.EMAIL_PASSWORD }}'
          host: 'smtp.gmail.com'
          port: 465
          secure: true
          from: 'GitHub workflows <maosenyang00@gmail.com>'
          to: 1960638223@qq.com,1694181697@qq.com
          # 判断所有任务是否成功执行。如果有失败的任务，则发送部署失败邮件，否则发送部署成功邮件。
          if: ${{ success() }}
          subject: 'Success：部署成功！'
          html: '<h2>所有工作流成功执行完毕！</h2>'

      - name: Send Mail 发送邮件
        uses: bingblue/send-nodemailer@master
        with:
          user: '${{ secrets.EMAIL_USERNAME }}'
          pass: '${{ secrets.EMAIL_PASSWORD }}'
          host: 'smtp.gmail.com'
          port: 465
          secure: true
          from: '构建与部署 <maosenyang00@gmail.com>'
          to: 1960638223@qq.com,1694181697@qq.com
          if: ${{ failure() }}
          subject: 'Failed：部署失败'
          html: '<h2>部署失败请重新检查代码</h2>'
