name: Notify and Alert

on:
  push:
    branches:
      - main

jobs:
  notify-and-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js and nodemailer
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install nodemailer
          npm install -g nodemailer-cli

      # 判断所有工作流是否成功执行
      - name: Check Workflow Status
        id: check_status
        run: |
          echo "::set-output name=success::true"
          if [[ $(grep "Job succeeded" $GITHUB_EVENT_PATH | wc -l) != 2 ]]; then
            echo "::set-output name=success::false"
          fi

      # 发送通知邮件
      - name: Send Mail
        uses: bingblue/send-nodemailer@master
        with:
          user: '${{ secrets.EMAIL_USERNAME }}'
          pass: '${{ secrets.EMAIL_PASSWORD }}'
          host: 'smtp.gmail.com'
          port: 465
          secure: true
          from: 'GitHub Action <maosenyang00@gmail.com>'
          to: 1960638223@qq.com,1694181697@qq.com
          # 根据工作流状态发送不同的邮件主题和内容
          subject: ${{ env.SUBJECT }}
          html: ${{ env.CONTENT }}
        env:
          SUBJECT: ${{ env.STATUS == 'success' && 'Success：GitHub Action run successfully' || 'Failed：GitHub Action failed to run' }}
          CONTENT: ${{ env.STATUS == 'success' && '<p>所有工作流成功执行完毕！</p>' || '<p>有失败的工作流</p>' }}
          STATUS: ${{ steps.check_status.outputs.success }}
